@startuml account_class

title Research Account Diagram
skinparam monochrome true

top to bottom direction

object Person {
  + name: "Nice Northcutt"
  + mbox: "nice_northcutt@email.com"
  
}

object Organization {
  + name: "Los Angeles College of Chiropractic"
}

object PropertyValue {
  + propertyID: "ORCID"
  + value: "7344-0227-6220-X"
}

object Account {
  + identifier: "nice_northcutt@test"
  + roleName: "reviewer"
  + publicKey: "9e5bf2e35b4355dc919f09e92d8bb49d2ffdda21c740c18433c3549071a41bea"
}

Person --|> Account
Person --|> Organization
Person --|> PropertyValue

@enduml