@startuml user_account_class

title Unified User Account Class Diagram
skinparam monochrome true

top to bottom direction

class User {
  + name: string
  + mbox: string
}

class Organization {
  + name: string
}

class PropertyValue {
  + propertyID: string
  + value: string
}

class Account {
  + identifier: string
  + roleName: string
  + publicKey: string
}

User --|> Account
User --|> Organization
User --|> PropertyValue

@enduml
