@startuml
title Research Account Diagram
skinparam monochrome true

object Person {
  + name: string
  + mbox: string
  + identifier: PropertyValue
}

object Organization {
  + name: string
}

object PropertyValue {
  + propertyID: string
  + value: string
}

object Account {
  + identifier: string
  + roleName: string
  + publicKey: string
}

Person --|> Account

Organization -- Person

Person -right-> Account




@enduml