@startuml account_class

title Account Diagram
skinparam monochrome true

top to bottom direction

class Person {
  + name: string
  + mbox: string
}

class Organization {
  + name: string
}

class PropertyValue {
  + propertyID: string
  + value: string
}

class Account {
  + identifier: string
  + roleName: string
  + publicKey: string
}

Person --|> Account
Person --|> Organization
Person --|> PropertyValue

@enduml