@startuml

skinparam monochrome true

title Open Science Platform - Artifact Management

participant User as "User"
participant Project as "Project"
participant Platform as "Platform"
participant Parser as "Metadata Parser"
participant Indexer as "Indexer"
participant IPFS as "IPFS"
participant Blockchain as "Blockchain"

User ->> Platform: Select local file
Platform ->> IPFS: Upload file
IPFS ->> Platform: Returns the file CID
Platform ->> Blockchain: Update the project account with the file CID
Platform ->> Parser: Sends the file for parsing
Parser ->> Platform: Returns parsed metadata
Platform ->> IPFS: Uploads metadata (JSON)
IPFS ->> Platform: Returns the metadata CID
Platform ->> Blockchain: Update the project account with the metadata CID
Platform ->> Indexer: Index file

@enduml
