@startuml

skinparam monochrome true

' title Open Science Platform - File Operations

participant User as "User"
participant Platform as "Platform"
participant Parser as "Metadata Parser"
participant Indexer as "Indexer"
participant IPFS as "IPFS"
participant Blockchain as "Blockchain"

User ->> Platform: Select local file to upload
Platform ->> Parser: Sends file for metadata extraction
Platform ->> Indexer: Index file
Parser ->> Platform: Returns metadata JSON object
Platform ->> IPFS: Uploads metadata JSON object
IPFS ->> Platform: Returns metadata JSON CID
Platform ->> IPFS: Upload file
IPFS ->> Platform: Returns file CID

Platform ->> Blockchain: Update the project account details with file and metadata CIDs


@enduml
