@startuml

skinparam monochrome true

' title Open Science Platform - User Enrollment and Project Registering

participant User as "User"
participant Platform as "Platform"
participant Blockchain as "Blockchain"

User ->> Platform: Enrolls
Platform ->> Blockchain: Create user account
User ->> Platform: Register project
Platform ->> Blockchain: Create project account


@enduml
