@startuml
'skinparam linetype ortho ' Removing ortho lines

title Centralized, Decentralized, and Distributed Systems

' Centralized System
rectangle "Centralized" {
  circle (60) as CS  ' Central Server - larger circle
  circle (20) as C1
  circle (20) as C2
  circle (20) as C3
  circle (20) as C4
  circle (20) as C5
  circle (20) as C6
  circle (20) as C7
  circle (20) as C8
  circle (20) as C9
  circle (20) as C10

  CS -- C1
  CS -- C2
  CS -- C3
  CS -- C4
  CS -- C5
  CS -- C6
  CS -- C7
  CS -- C8
  CS -- C9
  CS -- C10
}

' Decentralized System
rectangle "Decentralized" {
  circle (40) as CN1  ' Core Node - medium circle
  circle (40) as CN2
  circle (40) as CN3

  circle (20) as CN11
  circle (20) as CN12
  circle (20) as CN21
  circle (20) as CN22
  circle (20) as CN31
  circle (20) as CN32

  CN1 -- CN11
  CN1 -- CN12
  CN2 -- CN21
  CN2 -- CN22
  CN3 -- CN31
  CN3 -- CN32

  CN1 -- CN2
  CN2 -- CN3
  CN3 -- CN1
}

' Distributed System
rectangle "Distributed" {
  circle (30) as DN1  ' Distributed Node - smaller than central, but uniform
  circle (30) as DN2
  circle (30) as DN3
  circle (30) as DN4
  circle (30) as DN5
  circle (30) as DN6
  circle (30) as DN7

  DN1 -- DN2
  DN1 -- DN3
  DN2 -- DN3
  DN2 -- DN4
  DN3 -- DN5
  DN3 -- DN6
  DN4 -- DN7
  DN5 -- DN7
  DN6 -- DN7
}
@enduml
