@startuml
set separator none
title Open Science Platform - Containers

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<OpenSciencePlatform.Indexer>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}
skinparam database<<OpenSciencePlatform.IPFS>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}
skinparam rectangle<<OpenSciencePlatform.Blockchain>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}

skinparam rectangle<<OpenSciencePlatform.SearchEngine>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}

skinparam person<<User>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}
skinparam rectangle<<OpenSciencePlatform.MetadataExtractor>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}

skinparam rectangle<<OpenSciencePlatform.IPFSClient>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}

skinparam rectangle<<OpenSciencePlatform.IrohaClient>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}

skinparam rectangle<<OpenSciencePlatform.FrontEnd>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}

skinparam rectangle<<OpenSciencePlatform.SmartContract>> {
  BackgroundColor #F0F0F0
  FontColor #000000
  BorderColor #000000
  shadowing false
}
skinparam rectangle<<OpenSciencePlatform>> {
  BorderColor #000000
  FontColor #000000
  shadowing false
}

person "==User\n<size:10>[Person]</size>\n\nA researcher storing and collaborating on research data." <<User>> as User

rectangle "Open Science Platform\n<size:10>[Software System]</size>" <<OpenSciencePlatform>> {
  rectangle "==Front End\n<size:10>[Container: Jupyter Notebooks and Python]</size>\n\nUser self enrolls, authenticates, register projects and upload research data " <<OpenSciencePlatform.FrontEnd>> as OpenSciencePlatform.FrontEnd
  rectangle "==Indexer\n<size:10>[Container: Python]</size>\n\nIndexes file metadata for lookup" <<OpenSciencePlatform.Indexer>> as OpenSciencePlatform.Indexer
  rectangle "==Metadata Extractor\n<size:10>[Container: Apache Tika and Python]</size>\n\nExtracts metadata from files" <<OpenSciencePlatform.MetadataExtractor>> as OpenSciencePlatform.MetadataExtractor
  rectangle "==Iroha Client\n<size:10>[Container: Python]</size>\n\nIndexes file metadata for lookup" <<OpenSciencePlatform.IrohaClient>> as OpenSciencePlatform.IrohaClient
  rectangle "==IPFS Client\n<size:10>[Container: Apache Tika and Python]</size>\n\nExtracts metadata from files" <<OpenSciencePlatform.IPFSClient>> as OpenSciencePlatform.IPFSClient
  rectangle "==Search Engine\n<size:10>[Container: Apache Tika and Python]</size>\n\nExtracts metadata from files" <<OpenSciencePlatform.SearchEngine>> as OpenSciencePlatform.SearchEngine
  database "==Local File System\n<size:10>[Container: Hyperledger Iroha 1]</size>\n\nImmutably keep research records" <<OpenSciencePlatform.LocalFileSystem>> as OpenSciencePlatform.LocalFileSystem

}

  
rectangle "Persistency and Availaibility\n<size:10>[Software System]</size>" <<OpenSciencePlatform>> {
  database "==IPFS\n<size:10>[Container: Interplanetary File System]</size>\n\nStores project files and metadata" <<OpenSciencePlatform.IPFS>> as OpenSciencePlatform.IPFS
  database "==Blockchain\n<size:10>[Container: Hyperledger Iroha 1]</size>\n\nImmutably keep research records" <<OpenSciencePlatform.Blockchain>> as OpenSciencePlatform.Blockchain
  rectangle "==Smart Contract\n<size:10>[Container: Apache Tika and Python]</size>\n\nExtracts metadata from files" <<OpenSciencePlatform.SearchEngine>> as OpenSciencePlatform.SmartContract

}

User .[#707070,thickness=2].> OpenSciencePlatform.FrontEnd : "<color:#707070>Access Jupyter Notebook Server\n<color:#707070><size:8>[HTTPS]</size>"
OpenSciencePlatform.LocalFileSystem .[#707070,thickness=2].> OpenSciencePlatform.MetadataExtractor : "<color:#707070>Uploads research data"
OpenSciencePlatform.FrontEnd .[#707070,thickness=2].> OpenSciencePlatform.IrohaClient : "<color:#707070>Uploads research data"
OpenSciencePlatform.LocalFileSystem .[#707070,thickness=2].> OpenSciencePlatform.IPFSClient : "<color:#707070>Sends files for storage"
OpenSciencePlatform.MetadataExtractor .[#707070,thickness=2].> OpenSciencePlatform.Indexer : "<color:#707070>Sends JSON for indexing\n<color:#707070><size:8>[JSON/HTTPS]</size>"
OpenSciencePlatform.MetadataExtractor .[#707070,thickness=2].> OpenSciencePlatform.IPFSClient : "<color:#707070>Sends JSON for storage\n<color:#707070><size:8>[JSON/HTTPS]</size>"
OpenSciencePlatform.SmartContract .[#707070,thickness=2].> OpenSciencePlatform.Blockchain : "<color:#707070>Store Metadata CIDs\n<color:#707070><size:8>[JSON/HTTPS]</size>"
OpenSciencePlatform.IPFSClient .[#707070,thickness=2].> OpenSciencePlatform.IPFS : "<color:#707070>Store Metadata CIDs\n<color:#707070><size:8>[JSON/HTTPS]</size>"
OpenSciencePlatform.Indexer .[#707070,thickness=2].> OpenSciencePlatform.SearchEngine : "<color:#707070>Store Metadata CIDs\n<color:#707070><size:8>[JSON/HTTPS]</size>"
OpenSciencePlatform.FrontEnd .[#707070,thickness=2].> OpenSciencePlatform.LocalFileSystem : "<color:#707070>Store Metadata CIDs\n<color:#707070><size:8>[JSON/HTTPS]</size>"
OpenSciencePlatform.IrohaClient .[#707070,thickness=2].> OpenSciencePlatform.SmartContract : "<color:#707070>Store Metadata CIDs\n<color:#707070><size:8>[JSON/HTTPS]</size>"




@enduml

