@startuml entity_relationship_model

title Open Science Platform Entity-relationship model
skinparam monochrome true

top to bottom direction

entity "User" {
  + account_id: string 
  + full_name: string
  + email: string
  + institution: string
  + orcid: string
  + role: string
  + linked_project: string
}

entity "Project" {
  + id: string 
  + name: string
  + abstract: string
  + keywords: list<string>
  + startDate: date
  + endDate: date
  + city: string
  + country: string
  + linked_user: string
}

User  ||--o{ Project : is linked to 

@enduml
