@startuml
' title Hyperledger Iroha v1 Entity-relationship model(subset)
skinparam monochrome true

entity "account" {
    * account_id : string
    -- 
    domain_id : string
    quorum : int
    data : json
}

entity "domain" {
    * domain_id : string
    default_role : string
}

domain ||--o{ account : has  


@enduml
