@startuml
start
:Search for a keyword;
:Fetch keyword in the index;

if (Keyword found?) then (yes)
    :Get search results;
    :Fetch Project ID and File CID from search results;
    :Fetch Project ID account details in blockchain;

    :Parse Project account details;
    :Fetch File CID from Project account details;
    
    if (File CID from search results == File CID in Project account details in blockchain?) then (yes)
        :File is valid;
        :Download file from IPFS;
    else (no)
        :File is invalid;
    endif

else (no)
    :Keyword not found;
endif

stop
@enduml
