@startuml
start
:Search for a keyword;
:Fetch keyword in the index;

if (Keyword found?) then (Yes)
    :List Project ID and File CID;
    :Display file metadata;
    :Fetch Project ID account in blockchain;
    :Retrieve project owner from account details;
    :Fetch project owner account in blockchain;

    :Parse account details;
    :Fetch File Metadata CID;
    
    if (File Metadata CID in index == File Metadata CID in blockchain?) then (Yes)
        :File is valid;
    else (No)
        :File is invalid;
    endif

else (No)
    :Keyword not found;
endif

stop
@enduml
