@startuml

title Open Science indexing and validation

participant User as "User"
participant Platform as "Platform"
participant SE as "Search Engine"
participant Indexer as "Indexer"
participant IPFS as "IPFS"
participant Blockchain as "Blockchain"

User -> SE: Search Files by Keywords
SE -> Indexer: Parse the index for the keyword

Indexer -> Platform: Show results


alt Process Results
    
    Platform -> Blockchain: Fetch project details
    Blockchain -> Platform: Fetch corresponding Blockchain record

    Platform -> IPFS: Fetch IPFS file
    IPFS -> Platform: Confirm IPFS Record

    Platform -> Platform: Confirm file validation

end

IPFS -> User: Download File to Local File System

@enduml
