@startuml project_class

title Research Project Class Diagram
skinparam monochrome true

class "ResearchProject" {
  - identifier : string
  - publicKey : string
}

class "ProjectMetadata" {
  - name : string
  - abstract : string
  - keywords : list<string>
  - startDate : date
  - endDate : date
  - organization : Organization
  - city : string
  - country : string
}


ResearchProject -> ProjectMetadata : has metadata

@enduml